// Generated by make-bootstrap-snapshot.js. Do not edit by hand.
// Mirrors CLOUDFLARE_WORKERS_AI_MODEL in app/lib/workers-ai-model.ts.
export const WORKERS_AI_CODING_MODEL = "@cf/zai-org/glm-5.3-flash";
